# Generated by Django 4.2 on 2023-04-11 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_reunion', models.CharField(max_length=50)),
                ('fecha_hora', models.DateTimeField()),
                ('asistentes', models.ManyToManyField(related_name='asistencias', through='reuniones.Asistente', to='reuniones.usuario')),
                ('dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reuniones', to='reuniones.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='asistente',
            name='asistente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reuniones.usuario'),
        ),
        migrations.AddField(
            model_name='asistente',
            name='reunion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reuniones.reunion'),
        ),
    ]
